[Icon Theme]
Name=light
Comment=icon light theme for Boxee Simulator

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=24
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=24
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

# Directory list
Directories=actions/symbolic

[actions/symbolic]
Size=24
Context=actions
MinSize=16
MaxSize=512
Type=Scalable